"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .bankaccountdetails import BankAccountDetails
from .registeredaddress import RegisteredAddress
from dataclasses_json import Undefined, dataclass_json
from fx import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AutoSweepBankDetails:
    bank_account_details: Optional[BankAccountDetails] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('bankAccountDetails'), 'exclude': lambda f: f is None }})
    client_registered_address: Optional[RegisteredAddress] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('clientRegisteredAddress'), 'exclude': lambda f: f is None }})
    

