"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from .transactionrfidetailsresponse import TransactionRfiDetailsResponse
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from fx import utils
from typing import Dict, List, Optional

class ComplianceStatus(str, Enum):
    r"""This field contains the compliance status of the transaction.The possible values are:
    NULL
    IN_PROGRESS
    ACTION_REQUIRED
    RFI_REQUESTED
    RFI_RESPONDED
    COMPLETED
    ERROR
    REJECT
    EXPIRED
    """
    NONE = 'NONE'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    ACTION_REQUIRED = 'ACTION_REQUIRED'
    ERROR = 'ERROR'
    REJECT = 'REJECT'
    EXPIRED = 'EXPIRED'
    RFI_REQUESTED = 'RFI_REQUESTED'
    RFI_RESPONDED = 'RFI_RESPONDED'
    UNKNOWN = 'UNKNOWN'
    INITIATED = 'INITIATED'
    PENDING = 'PENDING'
    CLEAR = 'CLEAR'
    CLOSED = 'CLOSED'

class SettlementStatus(str, Enum):
    r"""This field contains the settlement status.This field can take the following values:
    Unsettled
    Settled
     Released
    Disputed
    DisputeClosed
    Waived
    """
    APPROVED = 'APPROVED'
    DECLINED = 'DECLINED'
    BLOCKED = 'BLOCKED'
    SETTLED = 'SETTLED'
    UNSETTLED = 'UNSETTLED'
    REVERSAL = 'REVERSAL'
    RELEASED = 'RELEASED'
    PENDING = 'PENDING'
    WAIVED = 'WAIVED'
    DISPUTED = 'DISPUTED'
    DISPUTE_CLOSED = 'DISPUTE_CLOSED'
    IN_PROGRESS = 'IN_PROGRESS'
    REJECTED = 'REJECTED'
    RETURNED = 'RETURNED'
    AWAITING_FUNDS = 'AWAITING_FUNDS'
    EXPIRED = 'EXPIRED'
    CANCELLED = 'CANCELLED'
    SCHEDULED = 'SCHEDULED'
    NA = 'NA'

class TransactionResponseDTOStatus(str, Enum):
    r"""This field contains the status. This field can take the following values:
    Pending: Transaction authorization is awaiting success or failure.
    Approved: Transaction is successfully authorized.
    Rejected: Transaction is rejected due to NIUM risk and compliance policies.
    Declined: Transaction is declined.
    Reversal: Transaction is reversed.
    Blocked: Transaction is blocked
    """
    APPROVED = 'APPROVED'
    DECLINED = 'DECLINED'
    BLOCKED = 'BLOCKED'
    SETTLED = 'SETTLED'
    UNSETTLED = 'UNSETTLED'
    REVERSAL = 'REVERSAL'
    RELEASED = 'RELEASED'
    PENDING = 'PENDING'
    WAIVED = 'WAIVED'
    DISPUTED = 'DISPUTED'
    DISPUTE_CLOSED = 'DISPUTE_CLOSED'
    IN_PROGRESS = 'IN_PROGRESS'
    REJECTED = 'REJECTED'
    RETURNED = 'RETURNED'
    AWAITING_FUNDS = 'AWAITING_FUNDS'
    EXPIRED = 'EXPIRED'
    CANCELLED = 'CANCELLED'
    SCHEDULED = 'SCHEDULED'
    NA = 'NA'

class TransactionType(str, Enum):
    r"""This field contains the transaction can be one of the complete list of transactions mentioned in [Transaction Types](doc:transactions#transaction-types)."""
    DEBIT = 'Debit'
    REVERSAL = 'Reversal'
    ORIGINAL_CREDIT = 'Original_Credit'
    ORIGINAL_CREDIT_REVERSAL = 'Original_Credit_Reversal'
    BALANCE_INQUIRY = 'Balance_Inquiry'
    PARTIAL_REVERSAL = 'Partial_Reversal'
    REVERSAL_ADVICE = 'Reversal_Advice'
    DECLINE_ADVICE = 'Decline_Advice'
    INCREMENTAL_AUTH_REVERSAL = 'Incremental_Auth_Reversal'
    AUTO_SWEEP = 'Auto_Sweep'
    AUTO_SWEEP_PAYOUT = 'Auto_Sweep_Payout'
    AUTO_SWEEP_PAYOUT_REVERSAL = 'Auto_Sweep_Payout_Reversal'
    SETTLEMENT_DEBIT = 'Settlement_Debit'
    SETTLEMENT_CREDIT = 'Settlement_Credit'
    SETTLEMENT_REVERSAL = 'Settlement_Reversal'
    SETTLEMENT_DIRECT_REVERSAL = 'Settlement_Direct_Reversal'
    SETTLEMENT_DIRECT_DEBIT = 'Settlement_Direct_Debit'
    FEE_DEBIT = 'Fee_Debit'
    FEE_REVERSAL = 'Fee_Reversal'
    FEE_WAIVER = 'Fee_Waiver'
    CLIENT_PREFUND = 'Client_Prefund'
    CLIENT_REFUND = 'Client_Refund'
    WALLET_REFUND = 'Wallet_Refund'
    WALLET_CREDIT_MODE_CARD = 'Wallet_Credit_Mode_Card'
    WALLET_CREDIT_MODE_PREFUND = 'Wallet_Credit_Mode_Prefund'
    WALLET_CREDIT_MODE_PREFUND_CROSS_CURRENCY = 'Wallet_Credit_Mode_Prefund_Cross_Currency'
    WALLET_CREDIT_MODE_OFFLINE = 'Wallet_Credit_Mode_Offline'
    WALLET_CREDIT_MODE_OFFLINE_CROSS_CURRENCY = 'Wallet_Credit_Mode_Offline_Cross_Currency'
    WALLET_CREDIT_MODE_OFFLINE_THIRD_PARTY = 'Wallet_Credit_Mode_Offline_ThirdParty'
    WALLET_CREDIT_MODE_DIRECT_DEBIT = 'Wallet_Credit_Mode_Direct_Debit'
    WALLET_CREDIT_MODE_DIRECT_DEBIT_REVERSAL = 'Wallet_Credit_Mode_Direct_Debit_Reversal'
    CUSTOMER_WALLET_CREDIT_FUND_TRANSFER = 'Customer_Wallet_Credit_Fund_Transfer'
    CUSTOMER_WALLET_DEBIT_FUND_TRANSFER = 'Customer_Wallet_Debit_Fund_Transfer'
    WALLET_FUND_TRANSFER = 'Wallet_Fund_Transfer'
    CLIENT_FUND_TRANSFER = 'Client_Fund_Transfer'
    WALLET_HOLD = 'Wallet_Hold'
    WALLET_UNHOLD = 'Wallet_Unhold'
    REMITTANCE_DEBIT = 'Remittance_Debit'
    REMITTANCE_DEBIT_EXTERNAL = 'Remittance_Debit_External'
    REMITTANCE_REVERSAL = 'Remittance_Reversal'
    REMITTANCE_CLIENT_AUTO_SWEEP = 'Remittance_Client_Auto_Sweep'
    REMITTANCE_CLIENT_AUTO_SWEEP_REVERSAL = 'Remittance_Client_Auto_Sweep_Reversal'
    REMITTANCE_DEBIT_PRESCREENING = 'Remittance_Debit_Prescreening'
    REMITTANCE_DEBIT_EXTERNAL_PRESCREENING = 'Remittance_Debit_External_Prescreening'
    REMITTANCE_BENE_MICRODEPOSIT = 'Remittance_Bene_Microdeposit'
    REMITTANCE_BENE_MICRODEPOSIT_REVERSAL = 'Remittance_Bene_Microdeposit_Reversal'
    REGULATORY_AUTO_SWEEP = 'Regulatory_Auto_Sweep'
    REGULATORY_BLOCK = 'Regulatory_Block'
    REGULATORY_BLOCK_RELEASE = 'Regulatory_Block_Release'
    REGULATORY_DEBIT = 'Regulatory_Debit'
    REGULATORY_DEBIT_REVERSAL = 'Regulatory_Debit_Reversal'
    TRANSFER_LOCAL = 'Transfer_Local'
    TRANSFER_LOCAL_REVERSAL = 'Transfer_Local_Reversal'
    CASHBACK_CREDIT = 'Cashback_Credit'
    CASHBACK_CREDIT_CLIENT = 'Cashback_Credit_Client'
    CHARGEBACK_CREDIT = 'Chargeback_Credit'
    CUSTOMER_WALLET_DEBIT_INTRA_REGION = 'Customer_Wallet_Debit_Intra_Region'
    CUSTOMER_WALLET_CREDIT_INTRA_REGION = 'Customer_Wallet_Credit_Intra_Region'
    CUSTOMER_WALLET_DEBIT_CROSS_REGION = 'Customer_Wallet_Debit_Cross_Region'
    CUSTOMER_WALLET_CREDIT_CROSS_REGION = 'Customer_Wallet_Credit_Cross_Region'
    DIRECT_DEBIT_PAYOUT = 'Direct_Debit_Payout'
    NA = 'NA'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TransactionResponseDTO:
    acquirer_country_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('acquirerCountryCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the country code of the acquirer."""
    acquiring_institution_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('acquiringInstitutionCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the acquiring institution code that identifies the financial institution acting as the acquirer of the transaction."""
    auth_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains an authorization amount of the transaction."""
    auth_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the authorization code."""
    auth_currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authCurrencyCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) of the auth currency, the currency in which amount is deducted from wallet."""
    billing_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('billingAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains the equivalent transaction amount in base currency."""
    billing_conversion_rate: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('billingConversionRate'), 'exclude': lambda f: f is None }})
    r"""This field contains the conversion rate of transaction currency to billing currency which is present for all card transactions."""
    billing_currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('billingCurrencyCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) for the billing currency or base currency"""
    billing_replacement_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('billingReplacementAmount'), 'exclude': lambda f: f is None }})
    r"""The corrected amount of a transaction in a partial reversal. This is defined by ISO-8583 as a fixed length field with four subfields, but only the first subfield is used. A 12 position field for the corrected, billing amount of a customer's transaction, in the billing currency. The field is right justified, with lead zero fill."""
    business_transaction: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('businessTransaction'), 'exclude': lambda f: f is None }})
    r"""This flag is used to mark or unmark a transaction as a business transaction."""
    card_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cardHashID'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique card identifier generated while new/add-on card issuance."""
    card_transaction_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cardTransactionAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains the amount of a card transaction."""
    child_customer_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('childCustomerHashId'), 'exclude': lambda f: f is None }})
    r"""This field refers to a unique identifier, known as customerHashId, assigned to an individual customer who is associated with a corporate customer at the parent level. This identifier serves the purpose of distinguishing and tracking the child-level customer within a given client's program. By utilizing this identifier, it becomes possible to establish and maintain the appropriate linkage between the child customer and their parent corporate customer, ensuring accurate association and management of customer data."""
    client_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('clientHashId'), 'exclude': lambda f: f is None }})
    r"""Unique client identifier generated and shared before API handshake."""
    comments: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('comments'), 'exclude': lambda f: f is None }})
    r"""This field contains the auto-generated comments with details on the transactions such as reason for transaction decline."""
    compliance_status: Optional[ComplianceStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('complianceStatus'), 'exclude': lambda f: f is None }})
    r"""This field contains the compliance status of the transaction.The possible values are:
    NULL
    IN_PROGRESS
    ACTION_REQUIRED
    RFI_REQUESTED
    RFI_RESPONDED
    COMPLETED
    ERROR
    REJECT
    EXPIRED
    """
    created_at: Optional[datetime] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('createdAt'), 'encoder': utils.datetimeisoformat(True), 'decoder': dateutil.parser.isoparse, 'exclude': lambda f: f is None }})
    r"""This field contains the date and time of transaction when created in UTC."""
    current_with_holding_balance: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('currentWithHoldingBalance'), 'exclude': lambda f: f is None }})
    r"""This field will be deprecated in the future."""
    customer_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('customerHashId'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique customer identifier generated while new customer created."""
    date_of_transaction: Optional[datetime] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dateOfTransaction'), 'encoder': utils.datetimeisoformat(True), 'decoder': dateutil.parser.isoparse, 'exclude': lambda f: f is None }})
    r"""This field contains the date on which the transaction occurred in yyyy-MM-dd format."""
    debit: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('debit'), 'exclude': lambda f: f is None }})
    r"""This field contains the flag signifies if the transaction is a debit transaction."""
    effective_auth_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('effectiveAuthAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains an effective authorization amount which includes fees, markup, etc."""
    labels: Optional[Dict[str, str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('labels'), 'exclude': lambda f: f is None }})
    r"""This object will contain different key-value pairs depending upon the type of transaction. Essentially, this object will contain different labels based on the type of transaction. The list will change over time depending on different use-cases. Refer to the [Glossary of Labels](/apis/docs/transaction-response-labels)."""
    local_date: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('localDate'), 'exclude': lambda f: f is None }})
    r"""This field contains the local date of the transaction."""
    local_time: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('localTime'), 'exclude': lambda f: f is None }})
    r"""This field contains the local time of the transaction."""
    masked_card_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('maskedCardNumber'), 'exclude': lambda f: f is None }})
    r"""This field contains the 16-digit masked card number in format 1234-56xx-xxxx-3456."""
    mcc: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('mcc'), 'exclude': lambda f: f is None }})
    r"""This field contains the four-digit Merchant Category Code."""
    merchant_category: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantCategory'), 'exclude': lambda f: f is None }})
    r"""This field contains the merchant category such as Airlines, Hotels, Shopping, etc."""
    merchant_city: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantCity'), 'exclude': lambda f: f is None }})
    r"""This field contains the city name of the merchant."""
    merchant_country: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantCountry'), 'exclude': lambda f: f is None }})
    r"""This field contains the country of the merchant."""
    merchant_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantID'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique merchant identifier."""
    merchant_latitude: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantLatitude'), 'exclude': lambda f: f is None }})
    r"""This field contains the latitude of the merchant captured during geo-tagging."""
    merchant_longitude: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantLongitude'), 'exclude': lambda f: f is None }})
    r"""This field contains the longitude of the merchant captured during geo-tagging."""
    merchant_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantName'), 'exclude': lambda f: f is None }})
    r"""This field contains the name of the merchant."""
    merchant_name_location: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantNameLocation'), 'exclude': lambda f: f is None }})
    r"""This field contains the full merchant name and location data as received from network."""
    merchant_tagged_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantTaggedName'), 'exclude': lambda f: f is None }})
    r"""This field contains the tagged name of the merchant."""
    merchant_zoom_index: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchantZoomIndex'), 'exclude': lambda f: f is None }})
    r"""This field contains the merchant map zoom index."""
    original_authorization_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('originalAuthorizationCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the authorization code of the original transaction in case of reversal."""
    partner_reference_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('partnerReferenceNumber'), 'exclude': lambda f: f is None }})
    r"""This field contains the provided by an RHA client in response to an authorization."""
    payment_instrument_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('paymentInstrumentHashId'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique payment instrument identifier generated for the linked card."""
    pos_condition_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('posConditionCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the pos condition code that describes the condition under which the transaction takes place at the point of service.
    00 - Normal transaction
    01 - Cardholder not present
    03 - Merchant suspicious
    08 - Mail/telephone order
    51 - Account Verification Message(AVM)
    55 - ICC Capable Branch ATM
    59 - Electronic Commerce
    90 - Recurring Payment
    """
    pos_entry_capability_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('posEntryCapabilityCode'), 'exclude': lambda f: f is None }})
    r"""This field provides information about the terminal used at the point of service.Type of terminal field values include:0 - Unspecified
    2 - Unattended terminal(customer-operated)
    4 - Electronic cash register
    7 - Telephone device
    8 - MCAS device
    9 - Mobile acceptance solution(mPOS)
    Capability of terminal field values include:
    0 - Unspecified
    1 - Terminal not used
    2 - Magnetic stripe read capability
    3 - Bar code read capability
    4 - OCR read capability
    5 - Integrated circuit card read capability
    9 - Terminal does not read card data
    """
    pos_entry_mode: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('posEntryMode'), 'exclude': lambda f: f is None }})
    r"""This field contains the pos entry code that identifies the actual method used to capture the account number and expiration date, and the PIN capture capability of the terminal.This is a fixed‑length field with three subfields, as follows:
    1. Positions 1‑2 - PAN and Date Entry Mode: This is a two‑digit code that identifies the actual method used at the point of service to enter the cardholder account number and card expiry date.
    00 - Unknown
    01 - Keyed transaction
    02 - Magnetic stripe read
    05 - Chip was read at the terminal
    07 - Contactless
    90 - Magnetic stripe read and transmitted unaltered
    91 - Contactless - Magnetic stripe data (MSD) transmitted
    2. Position 3 - PIN Entry Capability: This is a one‑digit code that identifies the capability of the authorization terminal, if one was used, to capture PINs. This coding does not necessarily mean that a PIN was entered or is included in this message:
    0 - Unknown
    1 - Terminal can accept PINs
    2 - Terminal cannot accept PINs
    3 - mPOS terminal can accept software-based PINs (Mastercard only)
    3. Position 4 - Unused(filler): This is one digit of filler, which must be zero.
    """
    previous_balance: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('previousBalance'), 'exclude': lambda f: f is None }})
    r"""This field contains the previous balance in the wallet."""
    processing_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('processingCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the processing code is a 6 character Visa field. Refer to the [link](https://en.wikipedia.org/wiki/ISO_8583#Processing_code) for more details on the processing code."""
    receipt_file_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('receiptFileName'), 'exclude': lambda f: f is None }})
    r"""This field contains the name of the receipt file."""
    receipt_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('receiptType'), 'exclude': lambda f: f is None }})
    r"""This field contains the receipt type.Expected values are as follows:
    image/png
    image/jpg
    image/jpeg
    application/pdf
    """
    retrieval_reference_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('retrievalReferenceNumber'), 'exclude': lambda f: f is None }})
    r"""This field contains the 12 digit number that is used with other data elements as a key to identify and track all messages related to a given customer transaction."""
    rfi_details: Optional[List[TransactionRfiDetailsResponse]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('rfiDetails'), 'exclude': lambda f: f is None }})
    r"""This field is an array that holds RFI details."""
    rha_transaction_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('rhaTransactionId'), 'exclude': lambda f: f is None }})
    r"""This field contains the transaction Id for an RHA client."""
    settlement_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains the settlement amount of a transaction. This amount is valid only for a settled transaction."""
    settlement_auth_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementAuthAmount'), 'exclude': lambda f: f is None }})
    r"""This field contains the settlement auth amount of a transaction. This amount is valid only for a settled transaction."""
    settlement_billing_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementBillingAmount'), 'exclude': lambda f: f is None }})
    settlement_currency: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementCurrency'), 'exclude': lambda f: f is None }})
    settlement_date: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementDate'), 'exclude': lambda f: f is None }})
    r"""This field contains the settlement date in case of a Settled transaction. Otherwise, it is null."""
    settlement_status: Optional[SettlementStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementStatus'), 'exclude': lambda f: f is None }})
    r"""This field contains the settlement status.This field can take the following values:
    Unsettled
    Settled
     Released
    Disputed
    DisputeClosed
    Waived
    """
    settlement_transaction_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('settlementTransactionAmount'), 'exclude': lambda f: f is None }})
    status: Optional[TransactionResponseDTOStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""This field contains the status. This field can take the following values:
    Pending: Transaction authorization is awaiting success or failure.
    Approved: Transaction is successfully authorized.
    Rejected: Transaction is rejected due to NIUM risk and compliance policies.
    Declined: Transaction is declined.
    Reversal: Transaction is reversed.
    Blocked: Transaction is blocked
    """
    system_trace_audit_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('systemTraceAuditNumber'), 'exclude': lambda f: f is None }})
    r"""This field contains the system trace audit number assigned to uniquely identify a transaction."""
    tags: Optional[Dict[str, str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tags'), 'exclude': lambda f: f is None }})
    r"""This object contains the user defined key-value pairs provided by the client."""
    terminal_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminalID'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique terminal ID."""
    transaction_currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactionCurrencyCode'), 'exclude': lambda f: f is None }})
    r"""This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) for the transaction currency."""
    transaction_replacement_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactionReplacementAmount'), 'exclude': lambda f: f is None }})
    r"""The corrected amount of a transaction in a partial reversal. This is defined by ISO-8583 as a fixed length field with four subfields, but only the first subfield is used. A 12 position field for the corrected, actual amount of a customer's transaction, in the transaction currency. The field is right justified, with lead zero fill."""
    transaction_type: Optional[TransactionType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactionType'), 'exclude': lambda f: f is None }})
    r"""This field contains the transaction can be one of the complete list of transactions mentioned in [Transaction Types](doc:transactions#transaction-types)."""
    updated_at: Optional[datetime] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('updatedAt'), 'encoder': utils.datetimeisoformat(True), 'decoder': dateutil.parser.isoparse, 'exclude': lambda f: f is None }})
    r"""This field contains the date and time when the transaction was last updated in UTC."""
    wallet_hash_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('walletHashId'), 'exclude': lambda f: f is None }})
    r"""This field contains the unique wallet identifier generated while new wallet created."""
    

